class Worker {
  final String name;
  final String location;
  final String contact;
  final List<String> skills;
  final double score;
  final int rank;
  double averageRating; // New property to track the rating
  int ratingCount; // New property to track the number of ratings

  Worker({
    required this.name,
    required this.location,
    required this.contact,
    required this.skills,
    required this.score,
    required this.rank,
    this.averageRating = 0,
    this.ratingCount = 0,
  });
}

List<Worker> workers = [
  Worker(
    name: "John Doe",
    location: "Tshwane",
    contact: "082 345 6789",
    skills: ["Cleaning", "Pet sitting"],
    score: 97.8,
    rank: 1,
    averageRating: 2.3,
    ratingCount: 34,
  ),
    Worker(
    name: "Jane Smith",
    location: "Tshwane",
    contact: "082 345 6788",
    skills: ["Gardening", "Construction"],
    score: 95.3,
    rank: 2,
    averageRating: 1.3,
    ratingCount: 40,
  ),
  Worker(
    name: "Mike Brown",
    location: "Pretoria",
    contact: "072 555 1234",
    skills: ["Till Worker", "Customer Service"],
    score: 90.4,
    rank: 3,
    averageRating: 4.3,
    ratingCount: 20,
  ),
  Worker(
    name: "Sara Khan",
    location: "Johannesburg",
    contact: "073 678 9012",
    skills: ["Till Worker", "Customer Service"],
    score: 88.6,
    rank: 4,
    averageRating: 4.1,
    ratingCount: 12,
  ),
  Worker(
    name: "Alice Green",
    location: "Soweto",
    contact: "082 987 6543",
    skills: ["Domestic Help", "Cleaning"],
    score: 92.3,
    rank: 6,
    averageRating: 4.6,
    ratingCount: 20,
  ),
  Worker(
    name: "David Black",
    location: "Randburg",
    contact: "071 234 5678",
    skills: ["Construction", "Carpentry"],
    score: 87.2,
    rank: 7,
    averageRating: 4.4,
    ratingCount: 16,
  ),
  Worker(
    name: "Emily White",
    location: "Sandton",
    contact: "084 321 8765",
    skills: ["Gardening", "Landscaping"],
    score: 89.0,
    rank: 8,
    averageRating: 4.2,
    ratingCount: 22,
  ),
  Worker(
    name: "Peter Gray",
    location: "Midrand",
    contact: "079 654 3210",
    skills: ["Till Worker", "Retail Assistant"],
    score: 84.3,
    rank: 9,
    averageRating: 3.8,
    ratingCount: 19,
  ),
  Worker(
    name: "Nina Blue",
    location: "Cape Town",
    contact: "076 789 0123",
    skills: ["Petrol Help", "Garage Assistance"],
    score: 83.5,
    rank: 10,
    averageRating: 3.7,
    ratingCount: 21,
  ),
  Worker(
    name: "Musa Mkhize",
    location: "Durban",
    contact: "082 123 4567",
    skills: ["Gardening", "Landscaping"],
    score: 91.5,
    rank: 11,
    averageRating: 4.4,
    ratingCount: 25,
  ),
  Worker(
    name: "Thabo Dlamini",
    location: "Pretoria",
    contact: "083 987 6543",
    skills: ["Construction", "Masonry"],
    score: 89.7,
    rank: 12,
    averageRating: 4.2,
    ratingCount: 18,
  ),
  Worker(
    name: "Zanele Ntuli",
    location: "Johannesburg",
    contact: "073 456 7890",
    skills: ["Domestic Help", "Childcare"],
    score: 93.2,
    rank: 13,
    averageRating: 4.7,
    ratingCount: 30,
  ),
  Worker(
    name: "Bongani Nkosi",
    location: "Tembisa",
    contact: "072 321 6549",
    skills: ["Petrol Help", "Garage Assistant"],
    score: 84.8,
    rank: 14,
    averageRating: 3.9,
    ratingCount: 22,
  ),
  Worker(
    name: "Ayanda Gwala",
    location: "Polokwane",
    contact: "082 765 4321",
    skills: ["Till Worker", "Retail Assistance"],
    score: 88.1,
    rank: 15,
    averageRating: 4.1,
    ratingCount: 20,
  ),
  Worker(
    name: "Sipho Zondi",
    location: "East London",
    contact: "074 543 2109",
    skills: ["Gardening", "Landscaping"],
    score: 86.4,
    rank: 16,
    averageRating: 4.0,
    ratingCount: 23,
  ),
  Worker(
    name: "Lindiwe Molefe",
    location: "Soweto",
    contact: "076 234 5678",
    skills: ["Domestic Help", "Cleaning"],
    score: 92.8,
    rank: 17,
    averageRating: 4.6,
    ratingCount: 28,
  ),
  Worker(
    name: "Patrick Mokoena",
    location: "Pretoria",
    contact: "082 234 5678",
    skills: ["Construction", "Bricklaying"],
    score: 85.2,
    rank: 18,
    averageRating: 3.8,
    ratingCount: 16,
  ),
  Worker(
    name: "Nosipho Zulu",
    location: "Durban",
    contact: "072 765 4321",
    skills: ["Domestic Help", "Pet Sitting"],
    score: 94.0,
    rank: 19,
    averageRating: 4.8,
    ratingCount: 35,
  ),
  Worker(
    name: "Khwezi Mbatha",
    location: "Cape Town",
    contact: "083 543 2109",
    skills: ["Gardening", "Plant Care"],
    score: 87.3,
    rank: 20,
    averageRating: 4.1,
    ratingCount: 19,
  ),
  Worker(
    name: "Andile Ncube",
    location: "Midrand",
    contact: "074 654 3210",
    skills: ["Petrol Help", "Mechanic Assistance"],
    score: 83.1,
    rank: 21,
    averageRating: 3.7,
    ratingCount: 17,
  ),
  Worker(
    name: "Thandiwe Ndlovu",
    location: "Johannesburg",
    contact: "084 432 1098",
    skills: ["Domestic Help", "Housekeeping"],
    score: 90.2,
    rank: 22,
    averageRating: 4.3,
    ratingCount: 26,
  ),
  Worker(
    name: "Simphiwe Maseko",
    location: "Pretoria",
    contact: "082 321 0987",
    skills: ["Till Worker", "Customer Service"],
    score: 86.9,
    rank: 23,
    averageRating: 4.0,
    ratingCount: 21,
  ),
  Worker(
    name: "Vusi Mthethwa",
    location: "Durban",
    contact: "072 543 2109",
    skills: ["Construction", "Roofing"],
    score: 88.7,
    rank: 24,
    averageRating: 4.2,
    ratingCount: 18,
  ),
  Worker(
    name: "Ntokozo Sithole",
    location: "Polokwane",
    contact: "073 321 6543",
    skills: ["Gardening", "Landscaping"],
    score: 85.6,
    rank: 25,
    averageRating: 3.9,
    ratingCount: 15,
  ),
  Worker(
    name: "Mbali Ngcobo",
    location: "Johannesburg",
    contact: "083 765 4321",
    skills: ["Domestic Help", "Cooking"],
    score: 91.4,
    rank: 26,
    averageRating: 4.5,
    ratingCount: 32,
  ),
  Worker(
    name: "Kagiso Mkhwanazi",
    location: "Cape Town",
    contact: "084 654 3210",
    skills: ["Petrol Help", "Garage Assistance"],
    score: 84.0,
    rank: 27,
    averageRating: 3.8,
    ratingCount: 14,
  ),
  Worker(
    name: "Zodwa Shabalala",
    location: "Soweto",
    contact: "076 543 2109",
    skills: ["Gardening", "Plant Care"],
    score: 88.9,
    rank: 28,
    averageRating: 4.2,
    ratingCount: 25,
  ),
  Worker(
    name: "Thembi Khoza",
    location: "Tshwane",
    contact: "073 765 4321",
    skills: ["Domestic Help", "Childcare"],
    score: 93.1,
    rank: 29,
    averageRating: 4.7,
    ratingCount: 36,
  ),
  Worker(
    name: "Bheki Dube",
    location: "Pretoria",
    contact: "082 432 1098",
    skills: ["Construction", "Painting"],
    score: 97.1,
    rank: 30,
    averageRating: 4.1,
    ratingCount: 23,
  ),
];


